// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot;

import java.util.HashMap;

import com.revrobotics.CANSparkMax;
import com.revrobotics.REVLibError;
import com.revrobotics.CANSparkBase.FaultID;
import com.revrobotics.CANSparkLowLevel.MotorType;

import edu.wpi.first.util.datalog.BooleanLogEntry;
import edu.wpi.first.util.datalog.DataLog;
import edu.wpi.first.util.datalog.DoubleLogEntry;
import edu.wpi.first.util.datalog.StringLogEntry;
import edu.wpi.first.wpilibj.DataLogManager;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj2.command.WrapperCommand;

/** Add your docs here. */
public class LogOrDash {
    private static DataLog l;

    private static HashMap<String, DoubleLogEntry> doubles;
    private static HashMap<String, BooleanLogEntry> booleans;
    private static HashMap<String, StringLogEntry> strings;

    public static boolean sendToDash;

    public static void setupLogging()
    {
        // Start data logging
        DataLogManager.start();
        DriverStation.startDataLog(DataLogManager.getLog());

        l = DataLogManager.getLog();

        doubles = new HashMap<String, DoubleLogEntry>();
        booleans = new HashMap<String, BooleanLogEntry>();
        strings = new HashMap<String, StringLogEntry>();

        sendToDash = true;

        
    }

    public static void logNumber(String key, double value)
    {
        if(sendToDash)
        {
            SmartDashboard.putNumber(key, value);
        }
        else
        {
            DoubleLogEntry d = doubles.get(key);
            if(d != null)
            {
                d.append(value);
            }
            else
            {
                d = new DoubleLogEntry(l, "NT:/SmartDashboard/"+key);
                d.append(value);
                doubles.put(key, d);
            }
        }
    }

    
    public static void logBoolean(String key, boolean value)
    {
        if(sendToDash)
        {
            SmartDashboard.putBoolean(key, value);
        }
        else
        {
            BooleanLogEntry d = booleans.get(key);
            if(d != null)
            {
                d.append(value);
            }
            else
            {
                d = new BooleanLogEntry(l, "NT:/SmartDashboard/"+key);
                d.append(value);
                booleans.put(key, d);
            }
        }
    }

    
    public static void logString(String key, String value)
    {
        if(sendToDash)
        {
            SmartDashboard.putString(key, value);
        }
        else
        {
            StringLogEntry d = strings.get(key);
            if(d != null)
            {
                d.append(value);
            }
            else
            {
                d = new StringLogEntry(l, "NT:/SmartDashboard/"+key);
                d.append(value);
                strings.put(key, d);
            }
        }
    }

    public static WrapperCommand toggleDashboard()
    {
        return new InstantCommand(() -> {
            sendToDash = !sendToDash;
        }).ignoringDisable(true);
    }


    /**
     * Prints the status code generated by the given rev control command 
     * to the driver station. This is intended to be used when configuring motors, 
     * not on every frame when setting motor speeds!
     * 
     * @param name Name of this line to print (to track down what didn't work)
     * @param e Put your REVLib method call here
     */
    public static void checkRevError(String name, REVLibError e)
    {
        DriverStation.reportError(name+" result: "+
                e
                .name(), false);
    }


    /**
     * Log or send to dashboard diagnostic information about a SPARK MAX.
     * 
     * This does NOT include information from external sensors (encoders etc).
     * @param prefix Prefix string for this motor, ex: "arm/motor1"
     * @param s The CAN SPARK MAX to log diagnostics of
     */
    public static void sparkMaxDiagnostics(String prefix, CANSparkMax s)
    {
        // Motor temperature
        // Brushed motors won't have a connected internal thermister
        if(s.getMotorType() == MotorType.kBrushless)
        {
            logNumber(prefix+"/motorTemp", s.getMotorTemperature());
        }

        // Voltage & current data
        logNumber(prefix+"/outputCurrent", s.getOutputCurrent());
        logNumber(prefix+"/appliedOutput", s.getAppliedOutput());
        logNumber(prefix+"/busVoltage", s.getBusVoltage());

        // Error status
        logString(prefix+"/errors", s.getLastError().name());

        // Record faults and sticky faults
        logString(prefix+"/faults", decodeSparkMaxFaults(s.getFaults()));
        logString(prefix+"/faults", decodeSparkMaxFaults(s.getStickyFaults()));
        
    }

    /**
     * Decode SPARK MAX faults and sticky faults from a short
     * @param faults
     * @return String of faults, or empty string if none
     */
    private static String decodeSparkMaxFaults(short faultBits)
    {
        String faults = "";

        // Walk down the binary string, removing bits and adding to error string as we find them
        // TODO Skip one bit for negative numbers (unused) or get unsigned short instead?
        for(int i=15; i > 0; i--)
        {
            int x = (int) Math.pow(2, i);
            if(faultBits >= x)
            {
                faultBits -= x;
                FaultID f = FaultID.fromId(x);
                if(f != null)
                {
                    faults += f.name() + ", ";
                }
                else
                {
                    faults += ", unknown bit: "+x;
                }
            }
        }

        return faults;
    }
}
